language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install psycopg2-binary
script:
   #- pytest
  - flake8 tasks
  - pylint tasks
  - mypy --ignore-missing-imports .
